package id.ptkpn.retribusiapp.utils

const val BAKULAN = "bakulan"
const val PAKAI_MEJA = "pakai_meja"
const val PAKAI_KIOS = "pakai_kios"

const val PREF_KEY = "id.ptkpn.retribusiapp.PREFERENCE_KEY"
const val TRANSAKSI_DB = "transaksi.db"
const val TRANSAKSI_TABLE = "transaksi"
const val JURU_TAGIH_NAME = "juru_tagih_name"
const val JURU_TAGIH_ID = "juru_tagih_id"
const val IS_UPLOADED = "is_uploaded"

const val USERS = "users"
const val ROLE ="roles"
const val SUPERVISOR = "supervisor"
const val ADMIN = "admin"
const val TRANSAKSI_ID ="transaksi_id"
const val JENIS_PEDAGANG = "jenis_pedagang"
const val JUMLAH_BAYAR = "jumlah_bayar"
const val TOTAL_KESELURUHAN = "total_keseluruhan"
const val SELISIH = "selisih"
const val TANGGAL = "tanggal"
const val WAKTU = "waktu"
const val NAMA_JENIS = "nama_jenis"
const val TARIF = "tarif"
const val TRANSAKSI = "transaksi"
const val JUMLAH_BAKULAN = "jumlah_bakulan"
const val JUMLAH_PAKAI_KIOS = "jumlah_pakai_kios"
const val JUMLAH_PAKAI_MEJA = "jumlah_pakai_meja"
const val JUMLAH_DISETOR = "jumlah_disetor"
const val USER_ID = "user_id"
const val DETAIL_TRANSAKSI = "detail_transaksi"